### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by asimashfaq** [stephank/yarn-plugin-nixify#1]
When i do nix-build                                                                                                 
```
this derivation will be built:
  /nix/store/bpwny6vkff0mpd7hv22ywzcfd4xaiq62-myproject.drv
building '/nix/store/bpwny6vkff0mpd7hv22ywzcfd4xaiq62-myproject.drv'...

ErroSysError{executing '/nix/store/5i0vy593awrakrp55l87d5kb5rbvssaa-bash-4.4-p23/bin/bash': Argument list too long
```

**Comment by stephank** [comment]
Hi, thanks for reporting this issue!

I suspect this is just a large number of dependencies I hadn't tried with yet. Could you try with this version of the plugin and let me know if that works? https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/fix-args-too-long/dist/yarn-plugin-nixify.js

Thanks!

**Comment by stephank** [comment]
I just ran into this myself. It apparently didn't surface on my Mac, but does happen on Linux. I've merged the fixed, so a regular update of the plugin should also fix it now. :)
