### ISSUE TITLE
`.pnp.cjs` not copied

### ISSUE THREAD

**Issue by Clansty** [stephank/yarn-plugin-nixify#36]
I ran this package with default configuration and steps listed in README, but `.pnp.cjs` is not found in `result/libexec/<name>`

**Comment by Clansty** [comment]
I need to add these to overrideAttrs to fix this now

```
  installPhase = attrs.installPhase + ''
    cp /build/*/.pnp* "$out/libexec/$name"
  '';
```

**Comment by stephank** [comment]
Thanks for reporting this! It should be fixed if you upgrade the plugin now.
