### ISSUE TITLE
Avoid committing yarn-berry.cjs

### ISSUE THREAD

**Issue by loafofpiecrust** [stephank/yarn-plugin-nixify#4]
Hi! I just found this project and it's a pretty cool alternative to yarn2nix and node2nix. I'm wondering if there's any way that I can use Yarn v2/3 but avoid committing yarn-berry.cjs and avoid having the `yarn-project.nix` file depend on it? One issue right now is that I'm using flakes and they can only reference paths which are added to git, meaning I must commit yarn-berry.cjs for `yarn-project.nix` to pick it up. Thoughts?

**Comment by stephank** [comment]
Hi! 

I believe having the Yarn executable in git is how Yarn v2/3 is designed, and there's not really a way around it. As explained in [Installation](https://yarnpkg.com/getting-started/install#about-global-installs), Yarn considers itself another dependency of your project, and that dependency version should be locked like any other dependency. Difference is, the way Yarn locks its own version is by including the entire executable.

Ignoring Nix for a second, how are you managing your project with Yarn v2/3 if the executable is not in git? Does your `.yarnrc.yml` point to some path outside git? If not, how do you get your project up and running from a fresh `git clone`?

Inside a Nix build, I think what you want might be possible by adding a `preConfigure` hook that places the Yarn executable at the correct path (specified by `.yarnrc.yml`). You can get the executable using `fetchurl`, with a URL like: `https://repo.yarnpkg.com/3.0.2/packages/yarnpkg-cli/bin/yarn.js`
