### ISSUE TITLE
Not deterministic output: yarn-project.nix content

### ISSUE THREAD

**Issue by iccicci** [stephank/yarn-plugin-nixify#46]
Hi all,

I noticed that running `yarn` against the same project multiple times (even if in a short time period where no dependencies change in the npm registry) **may** result in generating two distinct `yarn-project.nix` files.

I checked this diff deeply and I noticed that the only change is the order of the generated `cacheEntries`; i.e. they are not sorted. I have two considerations.

1. this suggests me that for `nix` related purposes the order of `cacheEntries` is not relevant;
2. if we add `yarn-project.nix` to git, this may be cause of lots of merge conflicts which could be actually avoided if `cacheEntries` had a fixed order.

If my assumption (1) is correct, I would like to produce deterministic `yarn-project.nix` files to avoid merge conflicts.

Is my assumption correct?
In affermative case, is there a way to configure the the plugin to produce fixed sorted `cacheEntries` in `yarn-project.nix` or addressing this would require a change?

Thank you

**Comment by stephank** [comment]
I believe I fixed this a couple of weeks ago in 26d88f0295028f4fb1f1ddc7a77f93f432fc971a. Could you try updating the plugin to see if that fixes it?

**Comment by iccicci** [comment]
Checked and verified: I confirm.
Thank you very much @stephank !
