### ISSUE TITLE
Unrecognized configuration settings found: enableNixify

### ISSUE THREAD

**Issue by goldsborough** [stephank/yarn-plugin-nixify#59]
Hi,

Just starting out with this plugin. Also pretty new to Nix so bear with me. My package is pretty much the default:
```
{
  pkgs,
  flakeInputs,
  ...
}:
with pkgs;
pkgs.callPackage "${my_package_that_uses_yarn_plugin_nixify}/yarn-project.nix" { } { src = ./.; }
```

and I'm getting

```
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
Usage Error: Unrecognized or legacy configuration settings found: enableNixify - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)
```

after it spends a while trying to build. I'm running this with `nix-shell -p my_package_that_uses_yarn_plugin_nixify`.

What am I doing wrong?

**Comment by adrian-gierakowski** [comment]
It’s yarn complaining about a setting in .yarnrc

This would happen if the yarn-plugin-nixify was not found

**Comment by goldsborough** [comment]
Just to aid my debugging, (this only happens when I include my nix package inside a much larger nix codebase, not when I nix-build the package only), would yarn here expect to find the plugin in the .yarn folder that it's using (my suspicion is it's picking up the wrong .yarnrc or .yarn folder) -- just curious if you have any clues you would look for in debugging this?

**Comment by magthe** [comment]
I'm seeing this too and I'm having problems understanding just _why_ it happens. Especially since it works on my machine but fails in CI (GitHub Actions) and on my colleague's setup.

I have the following in my `flake.nix`:

```
{
  ...

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        yarnPkg = (pkgs.callPackage ./yarn-project.nix { } {
          src = pkgs.lib.cleanSource ./.;
        });

        thePkg = pkgs.stdenv.mkDerivation {
          ...
          nativeBuildInputs = [
            yarnPkg
            ...
          ];

          ...
        };

      in {
        packages.default = thePkg;

        devShells.default = pkgs.mkShell {
          inputsFrom = [ thePkg ];
        };
      });
}
```
