### ISSUE TITLE
Yarn 4 support

### ISSUE THREAD

**Issue by vladimirvolek** [stephank/yarn-plugin-nixify#73]
Any plans to support Yarn 4?

Thanks

**Comment by stephank** [comment]
I'd like to. I haven't look at API changes yet.

We also have to handle when `yarnPath` is null (the new default corepack scenario). We have to build a `fetchurl` call in that case, and simple take the hash from whatever Yarn is used to run the generator, which should be correct.

**Comment by stephank** [comment]
Main branch should now be compatible with both v3 and v4. 🙂
